name: build-and-sign

on:
  release:

jobs:
  release:
    runs-on: windows-latest
    defaults:
     run:
       shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Install osslsigncode
        run: |
          echo "$PWD/.local/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH
          set -eu
          mkdir -p .local/bin && cd .local/bin
          curl -sSL https://github.com/mtrojnar/osslsigncode/releases/download/2.1/osslsigncode_2.1_windows.zip -o osslsigncode.zip
          ls -l osslsigncode.zip
          unzip -j osslsigncode.zip
          ./osslsigncode --version || true

      - name: Build
        run: make windows_amd64_signed

      - name: Test
        run: make test

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .gotmp/bin/windows_amd64/sudo*.exe
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
